// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_sign_out.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignOutReq struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutReq) Reset()         { *m = SignOutReq{} }
func (m *SignOutReq) String() string { return proto.CompactTextString(m) }
func (*SignOutReq) ProtoMessage()    {}
func (*SignOutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6109d141e7fc572a, []int{0}
}

func (m *SignOutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutReq.Unmarshal(m, b)
}
func (m *SignOutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutReq.Marshal(b, m, deterministic)
}
func (m *SignOutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutReq.Merge(m, src)
}
func (m *SignOutReq) XXX_Size() int {
	return xxx_messageInfo_SignOutReq.Size(m)
}
func (m *SignOutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutReq proto.InternalMessageInfo

func (m *SignOutReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type SignOutRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutRes) Reset()         { *m = SignOutRes{} }
func (m *SignOutRes) String() string { return proto.CompactTextString(m) }
func (*SignOutRes) ProtoMessage()    {}
func (*SignOutRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6109d141e7fc572a, []int{1}
}

func (m *SignOutRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutRes.Unmarshal(m, b)
}
func (m *SignOutRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutRes.Marshal(b, m, deterministic)
}
func (m *SignOutRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutRes.Merge(m, src)
}
func (m *SignOutRes) XXX_Size() int {
	return xxx_messageInfo_SignOutRes.Size(m)
}
func (m *SignOutRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutRes.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignOutReq)(nil), "protocol.SignOutReq")
	proto.RegisterType((*SignOutRes)(nil), "protocol.SignOutRes")
}

func init() {
	proto.RegisterFile("auth_sign_out.proto", fileDescriptor_6109d141e7fc572a)
}

var fileDescriptor_6109d141e7fc572a = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0x2d, 0xc9,
	0x88, 0x2f, 0xce, 0x4c, 0xcf, 0x8b, 0xcf, 0x2f, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x0a, 0x5c, 0x5c, 0xc1, 0x99, 0xe9, 0x79, 0xfe, 0xa5,
	0x25, 0x41, 0xa9, 0x85, 0x42, 0x42, 0x5c, 0x2c, 0xa5, 0xc5, 0xa9, 0x45, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x12, 0x0f, 0x92, 0x8a, 0x62, 0x27, 0xee, 0x28, 0x4e, 0x7d, 0x98,
	0xe6, 0x24, 0x36, 0x30, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xe3, 0x39, 0x53, 0x64,
	0x00, 0x00, 0x00,
}
