// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_sign_up.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReq) Reset()         { *m = SignUpReq{} }
func (m *SignUpReq) String() string { return proto.CompactTextString(m) }
func (*SignUpReq) ProtoMessage()    {}
func (*SignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d945ca94665e0a8, []int{0}
}

func (m *SignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReq.Unmarshal(m, b)
}
func (m *SignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReq.Marshal(b, m, deterministic)
}
func (m *SignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReq.Merge(m, src)
}
func (m *SignUpReq) XXX_Size() int {
	return xxx_messageInfo_SignUpReq.Size(m)
}
func (m *SignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReq proto.InternalMessageInfo

func (m *SignUpReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignUpRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRes) Reset()         { *m = SignUpRes{} }
func (m *SignUpRes) String() string { return proto.CompactTextString(m) }
func (*SignUpRes) ProtoMessage()    {}
func (*SignUpRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d945ca94665e0a8, []int{1}
}

func (m *SignUpRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRes.Unmarshal(m, b)
}
func (m *SignUpRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRes.Marshal(b, m, deterministic)
}
func (m *SignUpRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRes.Merge(m, src)
}
func (m *SignUpRes) XXX_Size() int {
	return xxx_messageInfo_SignUpRes.Size(m)
}
func (m *SignUpRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRes.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignUpReq)(nil), "protocol.SignUpReq")
	proto.RegisterType((*SignUpRes)(nil), "protocol.SignUpRes")
}

func init() {
	proto.RegisterFile("auth_sign_up.proto", fileDescriptor_3d945ca94665e0a8)
}

var fileDescriptor_3d945ca94665e0a8 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2c, 0x2d, 0xc9,
	0x88, 0x2f, 0xce, 0x4c, 0xcf, 0x8b, 0x2f, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0xc9, 0xf9, 0x39, 0x52, 0x5c, 0xa5, 0xc5, 0xa9, 0x45, 0x10, 0x51, 0x25, 0x7d, 0x2e,
	0xce, 0xe0, 0xcc, 0xf4, 0xbc, 0xd0, 0x82, 0xa0, 0xd4, 0x42, 0x21, 0x25, 0x2e, 0x16, 0x90, 0x94,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0x9f, 0x1e, 0x4c, 0x87, 0x5e, 0x68, 0x71, 0x6a, 0x51,
	0x10, 0x58, 0x4e, 0x89, 0x1b, 0xa1, 0xa1, 0xd8, 0x89, 0x3b, 0x8a, 0x53, 0x1f, 0xa6, 0x28, 0x89,
	0x0d, 0xcc, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xe1, 0x36, 0x0c, 0x7d, 0x00, 0x00,
	0x00,
}
