// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_sign_in.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInReq) Reset()         { *m = SignInReq{} }
func (m *SignInReq) String() string { return proto.CompactTextString(m) }
func (*SignInReq) ProtoMessage()    {}
func (*SignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_850b0689abd51e59, []int{0}
}

func (m *SignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInReq.Unmarshal(m, b)
}
func (m *SignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInReq.Marshal(b, m, deterministic)
}
func (m *SignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInReq.Merge(m, src)
}
func (m *SignInReq) XXX_Size() int {
	return xxx_messageInfo_SignInReq.Size(m)
}
func (m *SignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignInReq proto.InternalMessageInfo

func (m *SignInReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignInRes struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRes) Reset()         { *m = SignInRes{} }
func (m *SignInRes) String() string { return proto.CompactTextString(m) }
func (*SignInRes) ProtoMessage()    {}
func (*SignInRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_850b0689abd51e59, []int{1}
}

func (m *SignInRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRes.Unmarshal(m, b)
}
func (m *SignInRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRes.Marshal(b, m, deterministic)
}
func (m *SignInRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRes.Merge(m, src)
}
func (m *SignInRes) XXX_Size() int {
	return xxx_messageInfo_SignInRes.Size(m)
}
func (m *SignInRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRes.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRes proto.InternalMessageInfo

func (m *SignInRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*SignInReq)(nil), "protocol.SignInReq")
	proto.RegisterType((*SignInRes)(nil), "protocol.SignInRes")
}

func init() {
	proto.RegisterFile("auth_sign_in.proto", fileDescriptor_850b0689abd51e59)
}

var fileDescriptor_850b0689abd51e59 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x2c, 0x2d, 0xc9,
	0x88, 0x2f, 0xce, 0x4c, 0xcf, 0x8b, 0xcf, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x00, 0x53, 0xc9, 0xf9, 0x39, 0x52, 0x5c, 0xa5, 0xc5, 0xa9, 0x45, 0x10, 0x51, 0x25, 0x7d, 0x2e,
	0xce, 0xe0, 0xcc, 0xf4, 0x3c, 0xcf, 0xbc, 0xa0, 0xd4, 0x42, 0x21, 0x25, 0x2e, 0x16, 0x90, 0x94,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0x9f, 0x1e, 0x4c, 0x87, 0x5e, 0x68, 0x71, 0x6a, 0x51,
	0x10, 0x58, 0x4e, 0x49, 0x11, 0xa1, 0xa1, 0x58, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0x3f, 0x3b, 0x35,
	0x0f, 0xac, 0x83, 0x33, 0x08, 0xc2, 0x71, 0xe2, 0x8e, 0xe2, 0xd4, 0x87, 0x69, 0x4d, 0x62, 0x03,
	0xb3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xe0, 0x75, 0xf2, 0x93, 0x00, 0x00, 0x00,
}
