// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: pose.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pose_Ping_FullMethodName         = "/protocol.Pose/Ping"
	Pose_AnalyseVideo_FullMethodName = "/protocol.Pose/AnalyseVideo"
)

// PoseClient is the client API for Pose service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoseClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error)
	AnalyseVideo(ctx context.Context, in *AnalyseVideoReq, opts ...grpc.CallOption) (*AnalyseVideoRes, error)
}

type poseClient struct {
	cc grpc.ClientConnInterface
}

func NewPoseClient(cc grpc.ClientConnInterface) PoseClient {
	return &poseClient{cc}
}

func (c *poseClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error) {
	out := new(PingRes)
	err := c.cc.Invoke(ctx, Pose_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poseClient) AnalyseVideo(ctx context.Context, in *AnalyseVideoReq, opts ...grpc.CallOption) (*AnalyseVideoRes, error) {
	out := new(AnalyseVideoRes)
	err := c.cc.Invoke(ctx, Pose_AnalyseVideo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoseServer is the server API for Pose service.
// All implementations must embed UnimplementedPoseServer
// for forward compatibility
type PoseServer interface {
	Ping(context.Context, *PingReq) (*PingRes, error)
	AnalyseVideo(context.Context, *AnalyseVideoReq) (*AnalyseVideoRes, error)
	mustEmbedUnimplementedPoseServer()
}

// UnimplementedPoseServer must be embedded to have forward compatible implementations.
type UnimplementedPoseServer struct {
}

func (UnimplementedPoseServer) Ping(context.Context, *PingReq) (*PingRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPoseServer) AnalyseVideo(context.Context, *AnalyseVideoReq) (*AnalyseVideoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyseVideo not implemented")
}
func (UnimplementedPoseServer) mustEmbedUnimplementedPoseServer() {}

// UnsafePoseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoseServer will
// result in compilation errors.
type UnsafePoseServer interface {
	mustEmbedUnimplementedPoseServer()
}

func RegisterPoseServer(s grpc.ServiceRegistrar, srv PoseServer) {
	s.RegisterService(&Pose_ServiceDesc, srv)
}

func _Pose_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoseServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pose_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoseServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pose_AnalyseVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyseVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoseServer).AnalyseVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pose_AnalyseVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoseServer).AnalyseVideo(ctx, req.(*AnalyseVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Pose_ServiceDesc is the grpc.ServiceDesc for Pose service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pose_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Pose",
	HandlerType: (*PoseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Pose_Ping_Handler,
		},
		{
			MethodName: "AnalyseVideo",
			Handler:    _Pose_AnalyseVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pose.proto",
}
