// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pose_analyse_video.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Joint int32

const (
	Joint_LEFT_SHOULDER  Joint = 0
	Joint_RIGHT_SHOULDER Joint = 1
	Joint_LEFT_ELBOW     Joint = 2
	Joint_RIGHT_ELBOW    Joint = 3
	Joint_LEFT_HIP       Joint = 4
	Joint_RIGHT_HIP      Joint = 5
	Joint_LEFT_KNEE      Joint = 6
	Joint_RIGHT_KNEE     Joint = 7
)

var Joint_name = map[int32]string{
	0: "LEFT_SHOULDER",
	1: "RIGHT_SHOULDER",
	2: "LEFT_ELBOW",
	3: "RIGHT_ELBOW",
	4: "LEFT_HIP",
	5: "RIGHT_HIP",
	6: "LEFT_KNEE",
	7: "RIGHT_KNEE",
}

var Joint_value = map[string]int32{
	"LEFT_SHOULDER":  0,
	"RIGHT_SHOULDER": 1,
	"LEFT_ELBOW":     2,
	"RIGHT_ELBOW":    3,
	"LEFT_HIP":       4,
	"RIGHT_HIP":      5,
	"LEFT_KNEE":      6,
	"RIGHT_KNEE":     7,
}

func (x Joint) String() string {
	return proto.EnumName(Joint_name, int32(x))
}

func (Joint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2ae94e5d1432e90e, []int{0}
}

type AnalyseVideoReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FrameStep            uint32   `protobuf:"varint,2,opt,name=frame_step,json=frameStep,proto3" json:"frame_step,omitempty"`
	Joints               []Joint  `protobuf:"varint,3,rep,packed,name=joints,proto3,enum=protocol.Joint" json:"joints,omitempty"`
	UseCached            bool     `protobuf:"varint,4,opt,name=use_cached,json=useCached,proto3" json:"use_cached,omitempty"`
	Video                []byte   `protobuf:"bytes,5,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyseVideoReq) Reset()         { *m = AnalyseVideoReq{} }
func (m *AnalyseVideoReq) String() string { return proto.CompactTextString(m) }
func (*AnalyseVideoReq) ProtoMessage()    {}
func (*AnalyseVideoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae94e5d1432e90e, []int{0}
}

func (m *AnalyseVideoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyseVideoReq.Unmarshal(m, b)
}
func (m *AnalyseVideoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyseVideoReq.Marshal(b, m, deterministic)
}
func (m *AnalyseVideoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyseVideoReq.Merge(m, src)
}
func (m *AnalyseVideoReq) XXX_Size() int {
	return xxx_messageInfo_AnalyseVideoReq.Size(m)
}
func (m *AnalyseVideoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyseVideoReq.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyseVideoReq proto.InternalMessageInfo

func (m *AnalyseVideoReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnalyseVideoReq) GetFrameStep() uint32 {
	if m != nil {
		return m.FrameStep
	}
	return 0
}

func (m *AnalyseVideoReq) GetJoints() []Joint {
	if m != nil {
		return m.Joints
	}
	return nil
}

func (m *AnalyseVideoReq) GetUseCached() bool {
	if m != nil {
		return m.UseCached
	}
	return false
}

func (m *AnalyseVideoReq) GetVideo() []byte {
	if m != nil {
		return m.Video
	}
	return nil
}

type AnalyseVideoRes struct {
	AnalysedFrames       [][]byte           `protobuf:"bytes,1,rep,name=analysed_frames,json=analysedFrames,proto3" json:"analysed_frames,omitempty"`
	Angles               []*EstimatedAngles `protobuf:"bytes,2,rep,name=angles,proto3" json:"angles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AnalyseVideoRes) Reset()         { *m = AnalyseVideoRes{} }
func (m *AnalyseVideoRes) String() string { return proto.CompactTextString(m) }
func (*AnalyseVideoRes) ProtoMessage()    {}
func (*AnalyseVideoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae94e5d1432e90e, []int{1}
}

func (m *AnalyseVideoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyseVideoRes.Unmarshal(m, b)
}
func (m *AnalyseVideoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyseVideoRes.Marshal(b, m, deterministic)
}
func (m *AnalyseVideoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyseVideoRes.Merge(m, src)
}
func (m *AnalyseVideoRes) XXX_Size() int {
	return xxx_messageInfo_AnalyseVideoRes.Size(m)
}
func (m *AnalyseVideoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyseVideoRes.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyseVideoRes proto.InternalMessageInfo

func (m *AnalyseVideoRes) GetAnalysedFrames() [][]byte {
	if m != nil {
		return m.AnalysedFrames
	}
	return nil
}

func (m *AnalyseVideoRes) GetAngles() []*EstimatedAngles {
	if m != nil {
		return m.Angles
	}
	return nil
}

type EstimatedAngles struct {
	Joint                Joint     `protobuf:"varint,1,opt,name=joint,proto3,enum=protocol.Joint" json:"joint,omitempty"`
	Angles               []float32 `protobuf:"fixed32,2,rep,packed,name=angles,proto3" json:"angles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EstimatedAngles) Reset()         { *m = EstimatedAngles{} }
func (m *EstimatedAngles) String() string { return proto.CompactTextString(m) }
func (*EstimatedAngles) ProtoMessage()    {}
func (*EstimatedAngles) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ae94e5d1432e90e, []int{2}
}

func (m *EstimatedAngles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EstimatedAngles.Unmarshal(m, b)
}
func (m *EstimatedAngles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EstimatedAngles.Marshal(b, m, deterministic)
}
func (m *EstimatedAngles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EstimatedAngles.Merge(m, src)
}
func (m *EstimatedAngles) XXX_Size() int {
	return xxx_messageInfo_EstimatedAngles.Size(m)
}
func (m *EstimatedAngles) XXX_DiscardUnknown() {
	xxx_messageInfo_EstimatedAngles.DiscardUnknown(m)
}

var xxx_messageInfo_EstimatedAngles proto.InternalMessageInfo

func (m *EstimatedAngles) GetJoint() Joint {
	if m != nil {
		return m.Joint
	}
	return Joint_LEFT_SHOULDER
}

func (m *EstimatedAngles) GetAngles() []float32 {
	if m != nil {
		return m.Angles
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.Joint", Joint_name, Joint_value)
	proto.RegisterType((*AnalyseVideoReq)(nil), "protocol.AnalyseVideoReq")
	proto.RegisterType((*AnalyseVideoRes)(nil), "protocol.AnalyseVideoRes")
	proto.RegisterType((*EstimatedAngles)(nil), "protocol.EstimatedAngles")
}

func init() {
	proto.RegisterFile("pose_analyse_video.proto", fileDescriptor_2ae94e5d1432e90e)
}

var fileDescriptor_2ae94e5d1432e90e = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xdd, 0x6e, 0xda, 0x40,
	0x10, 0x85, 0xbb, 0x36, 0x76, 0xf1, 0x00, 0xb6, 0x3b, 0xaa, 0xaa, 0xed, 0x45, 0x25, 0x0b, 0xa9,
	0xc2, 0xea, 0x05, 0x55, 0xe9, 0x13, 0x40, 0x6b, 0x0a, 0x0d, 0x0a, 0x68, 0xc9, 0x8f, 0x94, 0x1b,
	0xcb, 0xc1, 0x9b, 0x84, 0x08, 0xff, 0x84, 0x35, 0x91, 0xf2, 0x0c, 0x79, 0x8b, 0x3c, 0x69, 0xe4,
	0x31, 0x56, 0x12, 0x94, 0x2b, 0xef, 0x39, 0xe7, 0xd3, 0xcc, 0x19, 0x03, 0xcf, 0x33, 0x25, 0xc3,
	0x28, 0x8d, 0x36, 0x0f, 0x4a, 0x86, 0xf7, 0xeb, 0x58, 0x66, 0xfd, 0x7c, 0x9b, 0x15, 0x19, 0x36,
	0xe9, 0xb3, 0xca, 0x36, 0xdd, 0x27, 0x06, 0xce, 0xb0, 0x22, 0xce, 0x4a, 0x40, 0xc8, 0x3b, 0x44,
	0x68, 0xa4, 0x51, 0x22, 0x39, 0xf3, 0x98, 0x6f, 0x09, 0x7a, 0xe3, 0x37, 0x80, 0xab, 0x6d, 0x94,
	0xc8, 0x50, 0x15, 0x32, 0xe7, 0x9a, 0xc7, 0xfc, 0x8e, 0xb0, 0xc8, 0x59, 0x16, 0x32, 0xc7, 0x1e,
	0x98, 0xb7, 0xd9, 0x3a, 0x2d, 0x14, 0xd7, 0x3d, 0xdd, 0xb7, 0x07, 0x4e, 0xbf, 0xde, 0xd0, 0xff,
	0x5f, 0xfa, 0x62, 0x1f, 0x97, 0x73, 0x76, 0x4a, 0x86, 0xab, 0x68, 0x75, 0x23, 0x63, 0xde, 0xf0,
	0x98, 0xdf, 0x14, 0xd6, 0x4e, 0xc9, 0x3f, 0x64, 0xe0, 0x67, 0x30, 0xa8, 0x27, 0x37, 0x3c, 0xe6,
	0xb7, 0x45, 0x25, 0xba, 0xc9, 0x61, 0x47, 0x85, 0x3d, 0x70, 0xf6, 0x87, 0xc5, 0x21, 0xd5, 0x50,
	0x9c, 0x79, 0xba, 0xdf, 0x16, 0x76, 0x6d, 0x8f, 0xc9, 0xc5, 0x5f, 0x60, 0x46, 0xe9, 0xf5, 0x46,
	0x2a, 0xae, 0x79, 0xba, 0xdf, 0x1a, 0x7c, 0x7d, 0x69, 0x16, 0xa8, 0x62, 0x9d, 0x44, 0x85, 0x8c,
	0x87, 0x04, 0x88, 0x3d, 0xd8, 0x5d, 0x80, 0x73, 0x10, 0xe1, 0x77, 0x30, 0xe8, 0x00, 0xfa, 0x27,
	0xef, 0x9c, 0x57, 0xa5, 0xf8, 0xe5, 0xcd, 0x32, 0xad, 0x9e, 0xf8, 0xe3, 0x91, 0x81, 0x41, 0x20,
	0x7e, 0x82, 0xce, 0x2c, 0x18, 0x9f, 0x84, 0xcb, 0xc9, 0xfc, 0x74, 0xf6, 0x37, 0x10, 0xee, 0x07,
	0x44, 0xb0, 0xc5, 0xf4, 0xdf, 0xe4, 0x95, 0xc7, 0xd0, 0x06, 0x20, 0x2c, 0x98, 0x8d, 0xe6, 0xe7,
	0xae, 0x86, 0x0e, 0xb4, 0x2a, 0xa6, 0x32, 0x74, 0x6c, 0x43, 0x93, 0x80, 0xc9, 0x74, 0xe1, 0x36,
	0xb0, 0x03, 0x56, 0x15, 0x97, 0xd2, 0x28, 0x25, 0x85, 0x47, 0xc7, 0x41, 0xe0, 0x9a, 0xe5, 0xb0,
	0x2a, 0x25, 0xfd, 0x71, 0xd4, 0xba, 0xb0, 0x7e, 0xd6, 0xfd, 0x2f, 0x4d, 0x7a, 0xfd, 0x7e, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x65, 0x2d, 0x85, 0x17, 0x2d, 0x02, 0x00, 0x00,
}
